name: chess-server-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Download Stockfish Engine
        run: |
          mkdir -p module/internal/chess-engine/src/main/resources/engines/linux-x64
          curl -L -o stockfish.tar \
            https://github.com/official-stockfish/Stockfish/releases/latest/download/stockfish-ubuntu-x86-64-avx2.tar
          tar -xf stockfish.tar
          STOCKFISH_FILE=$(find . -type f -name "stockfish*" -executable | head -n 1)
          echo "Found engine: $STOCKFISH_FILE"
          mv "$STOCKFISH_FILE" module/internal/chess-engine/src/main/resources/engines/linux-x64/stockfish
          chmod +x module/internal/chess-engine/src/main/resources/engines/linux-x64/stockfish

      - name: Build bootJar
        run: ./gradlew :module:application:app-chess-api:bootJar

      - name: Upload built JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-chess-api-bootJar
          path: module/application/app-chess-api/build/libs/*.jar